import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ChakraProvider } from "@chakra-ui/react"
import theme from '../theme/theme'
import Footer from '../src/components/modules/footer/Footer'
import Head from 'next/head'
import Nav from '../src/components/modules/Nav/Nav'


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Datos vacunación Argentina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Nav/>
        <Component {...pageProps} />
        <Footer/>
      </ChakraProvider>
    </div>
    )
}
export default MyApp
